### ISSUE TITLE
一些大量级的规则貌似会报错

### ISSUE THREAD

**Issue by yt1988** [xxxbrian/Surge-Geosite#1]
首先感谢辛苦开发，这个比一些手动维护的规则集，及时性好太多了

例如

https://surge.bojin.co/geosite/category-ads-all

提示

Failed to generate Surge list: Failed to fetch sub-upstream content: Too many subrequests.

**Comment by xxxbrian** [comment]
这是由于 Cloudflare 免费计划的[子请求数量限制](https://developers.cloudflare.com/workers/platform/limits/#subrequests)引发的问题。部分规则集包含大量的 include 指令，递归时导致请求数量超出限制。当前已通过下载完整的 Geosite ZIP 包并在 Worker 内部解压的方式来减少请求次数([4fdff2c](https://github.com/xxxbrian/Surge-Geosite/commit/4fdff2c3fe2fd2e4ecf9ba3f5ef8c3ceb2007fd9#diff-ed9b82a41eafb2916053294532595ab1637a3e2564673da23e9f8985f4d93a36R29-R46))。不过，这种方法可能会略微增加每个边缘节点的首次请求时间。

**Comment by yt1988** [comment]
收到，再次感谢辛苦工作。

**Comment by xxxbrian** [comment]
目前测试所有大量级规则已完全可以正常工作了 🎉
